enableGlobalCache: true

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  zioroboco:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
