name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2270f39ef63c3edf50be34da68c039eca5e15c15
        with:
          version: 6.31.0
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
      - run: pnpm install --frozen-lockfile
      - uses: changesets/action@c3d88279fd9abe11410de073005e34863f735b1c
        with:
          title: Release
          commit: Release
          publish: pnpm release
          version: pnpm version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
